Update hugo.yaml

diff --git a/.github/workflows/hugo.yaml b/.github/workflows/hugo.yaml
--- a/.github/workflows/hugo.yaml
+++ b/.github/workflows/hugo.yaml
@@ -33,8 +33,19 @@ defaults:
     shell: bash
 
 jobs:
+  cleanup:
+    runs-on: ubuntu-latest
+    permissions: write-all
+    steps:
+      - name: Delete old deployments
+        uses: strumwolf/delete-deployment-environment@v2
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          environment: github-pages
+          onlyRemoveDeployments: true
   build:
     runs-on: ubuntu-latest
+    needs: cleanup
     if: github.actor != 'github-actions[bot]'
     permissions:
       actions: write
@@ -77,7 +88,7 @@ jobs:
             tex_file="$base.tex"
             if [ -f "$tex_file" ]; then
               dir=$(dirname "$tex_file")
-              mv "$pdf" "$dir/" || echo "Could not move $pdf"
+              mv -f "$pdf" "$dir/" || echo "Could not move $pdf"
             fi
           done
       - name: Commit generated PDFs
